name: ts-st
channels:
  - conda-forge
  - jkim-mlops
  - defaults
dependencies:
  - python >=3.13,<3.14

  # required
  - plotly >=6,<7
  - scikit-learn >=1.7,<2
  - statsmodels >=0.14,<1
  - streamlit >=1.52,<2
  - tradestation-python >=0.1.3,<1

  # linting
  - ruff